### ISSUE TITLE
[Suggestion] use Curios API for 1.13+

### ISSUE THREAD

**Issue by Linguardium** [Flanks255/simplybackpacks#11]
Currently Baubles does not support versions higher than 1.12
Curios API ( https://www.curseforge.com/minecraft/mc-mods/curios ) supports 1.13-1.15

**Comment by Flanks255** [comment]
I actually ran into this mod yesterday, its definitely on the list of things i want to add, just gotta get around to it.

**Comment by Mikeliro** [comment]
Any prevision?
https://github.com/TheIllusiveC4/Curios/wiki/How-to-Use:-Developers

**Comment by Flanks255** [comment]
its in the works.

**Comment by mrdeadlocked** [comment]
Curios support would be AWESOME

**Comment by Flanks255** [comment]
incoming PR: #30

**Comment by mrdeadlocked** [comment]
Great! Thanks! Now just to wait for a build

**Comment by Flanks255** [comment]
itll be a bit yet, gotta work out kinks in the PR, and get it all worked in.

**Comment by Flanks255** [comment]
Still planning on this eventually, but, its a bit trickier then baubles was...

**Comment by Flanks255** [comment]
Very soon...

**Comment by Flanks255** [comment]
Done in 2.0 for 1.16
