### ISSUE TITLE
Items disappearing when moving all of an item 

### ISSUE THREAD

**Issue by ghost** [Flanks255/simplybackpacks#12]
After moving all of one item into a backpack (by holding shift and double clicking,) the stacks convert to single items when the backpack is reopened. I've attached a gif of the issue occuring, it seems to happen more often when putting your items in the bottom half of the backpack.
![ezgif-2-7a49a43941a2](https://user-images.githubusercontent.com/59668131/77293143-bb8edc80-6caf-11ea-89de-1f2f71300e3f.gif)

forge-31.1.18, simplybackpacks-1.15.2-1.4.2.jar

**Comment by Flanks255** [comment]
Try updating to 1.4.3

**Comment by Flanks255** [comment]
Ya, this bug was fixed in 1.4.3.
