### ISSUE TITLE
Placing backpack on Bibliocraft shelf wipes all contents

### ISSUE THREAD

**Issue by Theoreticism** [Flanks255/simplybackpacks#14]
**Describe the bug**

- Hold a bag in your main hand.
- Right click on a Bibliocraft shelf to place the bag on the shelf.
- Right click on the shelf to retrieve the bag into your inventory.
- Bag inventory is now empty

**What I expected would happen**
Bag retains inventory when removed from shelf.

Note: I attempted this same process with a Thermal Expansion satchel, but the satchel retained its inventory.

**Versions**
Simply Backpacks 1.2.3 (in Dungeons, Dragons & Space Shuttles with many other mods)
Forge 14.23.5.2847

**Comment by Flanks255** [comment]
Interestingly, its contents are intact while inside the shelf, it only gets wiped if removed via right clicking directly, if you open the inventory of the shelf and remove it from the gui it is fine.
Not sure what bibliocraft is doing thats wiping the nbt data out, and given bibliocraft appears to be closed source i cant do a whole lot.

Unfortunately id say for now, just don't put it in a shelf.

**Comment by Flanks255** [comment]
Related:
https://github.com/Nuchaz/BiblioCraft/issues/681
