### ISSUE TITLE
[MC 1.15.2] Mod Interaction - Quark

### ISSUE THREAD

**Issue by TheUntamed** [Flanks255/simplybackpacks#15]
**Describe the bug**
When Quark mod is installed the inventory buttons added by it overlay some slots.

**Screenshots**
![Screenshot_1](https://user-images.githubusercontent.com/48363903/78453618-3635ff80-7693-11ea-908f-1cd43208f823.jpg)

I considered to post that on Quarks github, but I think it is much harder to change the button position for all possible interactions than just increasing the space between the inventory and  the backpack.

**Comment by Flanks255** [comment]
Fixed in:
1.12.2: 5385adc
1.14.4: 4234beb
1.15.2: e45a578
1.16.1: 8a70f77
