### ISSUE TITLE
Auto Pickup

### ISSUE THREAD

**Issue by fkrisi11** [Flanks255/simplybackpacks#17]
Could you explain how this feature works?
I don't understand how I can set up filters.

I imagined that if I set a filter for the backpack, the items I pick up go straight into the backpack.
But that was not the case.

Then I tried if the whitelist only allowed certain items to be stored in the backpack, but that was not the cause either.
So please.. explain these in detail.

**Comment by Flanks255** [comment]
There is a keybind you can set, too toggle auto pickup on and off.
in 1.15 there is also a gui switch on the filter window.

**Comment by fkrisi11** [comment]
I'm using 1.12.
I enabled the auto-pickup feature with a keybind, but it didn't help

**Comment by fkrisi11** [comment]
![bp](https://user-images.githubusercontent.com/26310365/79637531-9abb8900-8180-11ea-9035-ea70050e56a3.jpg)

I set the list up like this.
Then I enabled auto pickup.
Then I tried to pick up items.

I tried with the backpack in my inventory, and I also tried it, while the backpack was equipped in the baubles slot.

But I have seen no difference at all. I mean... I don't know what auto pickup does, as I couldn't get it to work

**Comment by Flanks255** [comment]
when enabled, items whitelisted should be pulled in when you pick them up, or if you have it set to blacklist, it should pick up everything but those items.

**Comment by fkrisi11** [comment]
So with those options on the picture I have sent, any stone drop that I pick up in the world, should go straight to the backpack, right?

**Comment by Flanks255** [comment]
Correct, if you have the filter set as such, and the auto pickup is enabled, IE, look at the tooltip of the backpack, it should say enabled or disabled on the auto pickup, and the backpack is in your hotbar, and you DO NOT have the gui open when you pick up the item then yes, it should pick it up.

if it doesnt, then some other mod is intercepting EntityItemPickupEvent

**Comment by fkrisi11** [comment]
Oh then some mod must be messing with the Item Pickup event

**Comment by fkrisi11** [comment]
Thanks for explaining ^^
That's all I wanted to know.
