### ISSUE TITLE
How does the filter work?

### ISSUE THREAD

**Issue by agentwolf88** [Flanks255/simplybackpacks#2]
How does the filter work? I press shift+right click, switch whitelist to on and put an item in. When i close the menu the whitelist is switching to off automaticly. What i do wrong?

sry for my english.

**Comment by Flanks255** [comment]
Ok, so apparently the NBT data of the filter does not save, if there are no existing tags, workaround till i get it fixed, is to toggle the auto pickup on, then your filter should save.

**Comment by Flanks255** [comment]
Fixed in 1.1.1
