### ISSUE TITLE
Not picking up whitelisted items

### ISSUE THREAD

**Issue by RepoDraghon** [Flanks255/simplybackpacks#21]
**Describe the bug**
The backpack will not pick up the whitelisted item if backpack is moved from the slot...

**Screenshots**
The vid will be at https://youtu.be/TRW9s5WUaTg

Please provide the version of the forge used and the mod version.
Forge 1.15.2 v1.77, Mod v1.4.5

**Comment by Flanks255** [comment]
Its been this way since 1.12, it only checks the hotbar for pickup targets, to avoid scanning the entire inventory every time an item is picked up.
if people really want it to i can make it scan the whole inventory, but no ones really brought it up.
