### ISSUE TITLE
Cannot put XP block or Heavy plated shield into simply backpacks

### ISSUE THREAD

**Issue by NielsPilgaard** [Flanks255/simplybackpacks#23]
**Describe the bug**
Certain items cannot be put inside the Backpacks:
* Heavy plated shield from Immersive Engineering 
* XP blocks from Global XP can be put inside only when no experience is stored

Please provide the version of forge used, and the mod version.
- Forge-1.14.4-28.2.16
- simplybackpacks-1.14.4-1.4.5

**Comment by Flanks255** [comment]
Those items must be tripping the nested item prevention code.
Which checks for:
- Itemhandler Capability
- an NBT Tag of "Items"
- an NBT Tag of "Inventory"
- an NBT Tag of "BlockEntityTag"

ill have to see whats up with those items.
