### ISSUE TITLE
Update GUI to be compatible with mods that adds sorting buttons

### ISSUE THREAD

**Issue by Onigeshi** [Flanks255/simplybackpacks#25]
With mods like Quark and maybe other inventory sorting mods, opening the GUI looks like this https://prnt.sc/tvyu3l .. increasing the space between the players inventory and the backpack inventory might solve these issues.. 

the buttons in question ( those in my screenshot ) are the ones that sort the players inventory and those on top, next to the inventory name are the ones that sorts the chest/backpack inventory.

**Comment by Flanks255** [comment]
Hm, i guess i forgot about this one... its come up before, and i thought i had done it already... lol

**Comment by Flanks255** [comment]
Duplicate of #15 Hopefully going to work on this this weekend.
