### ISSUE TITLE
[1.16.1] Open Backpack keybinding incorrectly opens backpack from other mod

### ISSUE THREAD

**Issue by NielsPilgaard** [Flanks255/simplybackpacks#26]
**Describe the bug**
Open Backpack keybinding incorrectly opens backpacks from the mod `Useful Backpacks`, but incorrectly. It cannot be interacted with, and it's name is `air`

**Screenshots**
![billede](https://user-images.githubusercontent.com/21295394/90985758-53a23200-e57e-11ea-992e-afa4bf7662c7.png)

### Versions
- Forge-1.16.1-32.0.108
- simplybackpacks-1.16.1-1.4.10

**Comment by Flanks255** [comment]
oh... thats not terrifying at all... sigh...

**Comment by NielsPilgaard** [comment]
It also renders the inventory as completely empty, so it may give people a bit of a shock :P

**Comment by Flanks255** [comment]
im loading up my dev env right now, im pretty sure it isnt opening another backpack, just opening... nothing lol...

**Comment by NielsPilgaard** [comment]
Of course :P but it only works with the Useful Backpack in the inventory.

**Comment by Flanks255** [comment]
oh, it does it without as well lol, i just tried it...

**Comment by NielsPilgaard** [comment]
That's odd, it's doesn't in Enigmatica 6.

**Comment by Flanks255** [comment]
which is weird, cause, i found the problem, and it totally should :P, problem is ive already got everything updated to 1.16.2

**Comment by Flanks255** [comment]
alright its fixed, ill push out a 1.15 and 1.16.2 update soon.

**Comment by NielsPilgaard** [comment]
Thanks :)
