### ISSUE TITLE
Upgrading a backpack causes it to lose all contents

### ISSUE THREAD

**Issue by Draskh** [Flanks255/simplybackpacks#3]
**Describe the bug**
Upgrading deltes all items inside the backpack.

**Comment by Flanks255** [comment]
Can you give me some more information?
Is this in single or multiplayer?
what mod version, forge version.
is this in a modpack? if so which one.

cause so far i cant reproduce it.

**Comment by Draskh** [comment]
I use Forge 2838 in singleplayer. I upgraded from to an Epic Backpack if this helps. And I have Bauble installed. 

Here is complete list of mods.
[mods.txt](https://github.com/Flanks255/simplybackpacks/files/3566985/mods.txt)

**Comment by Flanks255** [comment]
what kinda crafting table was it in? normal, tinkers AE2 terminal?

**Comment by Draskh** [comment]
I used a AE2 Crafting Terminal.

**Comment by Flanks255** [comment]
I'm not sure where along the line AE2 fixed the bug, but, its confirmed fixed in 1.16.1
