### ISSUE TITLE
Everything in my backpack disappeared?

### ISSUE THREAD

**Issue by wyethLee** [Flanks255/simplybackpacks#31]
I was having connection issues so I was logging on and off of a server, I had a full rare backpacks worth of stuff and it is all gone, I haven’t touched it and I didn’t drop the bag at any point. Help?

**Comment by Flanks255** [comment]
What version of the mod?

**Comment by wyethLee** [comment]
> What version of the mod?

1.15.2

**Comment by rendragnet** [comment]
I've had this happen twice today, was during passing the backpack between two players. When the original player received it back, the backpack was empty.  

MC: 1.15.2
SimplyBackpacks: 1.4.6

**Comment by rendragnet** [comment]
@Flanks255 You’re not interested in fixing bugs? :(

**Comment by Flanks255** [comment]
It's not that I'm not interested in fixing bugs, it's just I can't keep fixing older versions forever, adb thus type of bug is rarely reproducible.

**Comment by Flanks255** [comment]
While i cant guarantee its fixed it, i rolled all the bug fixes from the 1.16 version into the 1.15 version for one final update on the 1.15 version.

b291a59
