### ISSUE TITLE
Can't use 1.16.2

### ISSUE THREAD

**Issue by MunchyCrunchy** [Flanks255/simplybackpacks#32]
I can't make any of the backpacks or find them in creative mode.

**Comment by Flanks255** [comment]
What version of forge? what version of simply backpacks?

**Comment by MunchyCrunchy** [comment]
Forge 1.16.2 and simply backpacks 1.16.2 so everything is the same version.

**Comment by Flanks255** [comment]
Well, it definitely works in 1.16.2, they show up in the "tools" group, in the creative inventory. 
![image](https://user-images.githubusercontent.com/32142731/95657189-b02ec180-0ad8-11eb-9819-2a9b853abf96.png)
this is using:
forge: 33.0.61
and backpacks: 1.4.12

**Comment by MunchyCrunchy** [comment]
Ok ya I managed to find them in creative, before they hadn't shown up in search for some reason, but I still can't craft them (in creative or survival).

**Comment by Flanks255** [comment]
probably because i need to upload a new picture of the recipes, after 1.14 mojang changed to discrete dye items.
so instead of bone meal, the recipe now calls for white dye, etc.

i would also recommend installing JEI, so you can view the recipes.
