### ISSUE TITLE
Picked up items don't go to backpack

### ISSUE THREAD

**Issue by The1Tiger** [Flanks255/simplybackpacks#33]
As I was playing Minecraft, I had made several backpacks, all whitelisted with Auto-Pickup on, in order to sort out what I pick up into categories like - Mining, Farming, etc. However, I've realised that the bags only auto-pickup items IF the bags are in your hot-bar and NOT in your inventory. This is an extreme nuisance as I have too many backpacks to have them all in my inventory and my tools (sword, pickaxe, axe, etc).

I am currently in 1.16.3, mod version: 1.4.13, Forge: 34.1.14

**Comment by Flanks255** [comment]
Not really a bug unfortunately, that is the way they have always worked, and is intended.
Personally I only ever make one myself, others that make multiple just put them on their hotbar for quick access anyway.
Its kind of a balancing effect anyway, if you want extra inventory that auto pulls, gotta take up a hotbar slot.
