### ISSUE TITLE
Can't make backpack in survival, but it exists in creative.

### ISSUE THREAD

**Issue by StarProtocal** [Flanks255/simplybackpacks#34]
**Describe the bug**
 This is my only mod, also on singleplayer. I play on 1.16.4 and am using the latest verrsion of this mod which is 1.16.3
I am using Forge 35.1.0

**Comment by Flanks255** [comment]
The 1.16.3 version works on 1.16.4 as well, as for crafting it, remember that the way dyes work in minecraft changed awhile back, the recipes use the colored dyes, so in newer versions its white dye, not bone meal, etc 
![image](https://user-images.githubusercontent.com/32142731/99921606-166e4d00-2cf1-11eb-9f1c-0f547aaef615.png)

I highly recommend using Just Enough Items(JEI), to view recipes, it makes things alot easier.

**Comment by StarProtocal** [comment]
I'm on my way to test it if I have another issue. Thank you

**Comment by StarProtocal** [comment]
> I'm on my way to test it if I have another issue. Thank you

It works, thank you. 
How do you enable and disable auto pickup?

**Comment by Flanks255** [comment]
its an assignable hotkey.

**Comment by StarProtocal** [comment]
> its an assignable hotkey.

Thank you, Everything seems to be solved.
