### ISSUE TITLE
[1.16.3] - Backpack slots don't show up

### ISSUE THREAD

**Issue by kanauru** [Flanks255/simplybackpacks#35]
I managed to craft a backpack but the extra slots don't appear

Currently using 1.16.3-1.4.13

[image](https://user-images.githubusercontent.com/18458804/100925627-17dd0980-3497-11eb-8471-0e905f4aa328.png)

**Comment by Flanks255** [comment]
have you tried opening it?

**Comment by kanauru** [comment]
Sorry I just figured that out once I checked your video haha

Apologies for  being dumb 

Thanks!

**Comment by Flanks255** [comment]
:)
