### ISSUE TITLE
Item Duplication/Voiding Bug

### ISSUE THREAD

**Issue by aswgxf** [Flanks255/simplybackpacks#37]
**Describe the bug**
I noticed after sorting the backpack that I had two identical shears in there. I definitely did not have two shears, and if I somehow did, the chance that they'd both have the same damage value is slim. After noticing that I went to grab my exchanging gadget from the bag to charge it and found it wasn't there. I checked the storage system and it wasn't in there either. My guess is that when I sorted the bag it overwrote the exchanging gadget item with a copy of the shears. Not sure if this issue belongs to simply backpacks or inventory sorter, but I haven't seen it happen in any other inventories so I'm starting here. 

Forge version: 35.1.13
Simply Backpacks version: 1.16.3-1.4.13
Simple Inventory Sorter version: 18.1.0
Part of the Direwolf20 1.16 pack version 1.1.2

**Comment by Flanks255** [comment]
No idea, but i am about to release a new version soon with an entirely new backend system.
