### ISSUE TITLE
Backpack cannot be pulled out of the AE2 system

### ISSUE THREAD

**Issue by Mitko1239** [Flanks255/simplybackpacks#38]
**Describe the bug**
The backpack got stuck in the ME system and cannot be taken out with any mouse and keyboard interactions. It also cannot be pulled out with an interface.

**Screenshots**
![image](https://user-images.githubusercontent.com/1289999/105558987-ae4fdd80-5d18-11eb-83c0-4acc7e44c957.png)
Video:
https://streamable.com/rf1j6i

Forge version: 35.1.16
Simply Backpacks version: 1.16.3-1.4.13
Applied Energistics 2 version: 8.2.0-beta2
Part of the Direwolf20 1.16.4 pack version 1.4.1

**Comment by Flanks255** [comment]
This seems to be a problem with AE2 and large NBT data objects. while i cant get it to happen myself, i have no doubt that it does sometimes.
This happens commonly with Psi CAD's as well...
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/4816
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/4882

**Comment by Flanks255** [comment]
as a workaround, you should be able to pull it out with a AE2 personal chest(i think thats what its called) if you locate which drive its in, and put the drive into the chest, you should be able to pull it out with that(it works with psi guns).

**Comment by Mitko1239** [comment]
@Flanks255 I was able to pull it out on the next server start. BTW it was an empty backpack so I assume the NBT data wouldn't be that much.

Anyway, feel free to close this if you wish as that seems mostly an AE2 issue as you said.

**Comment by ozhound** [comment]
i came across this issue as well, just wanted to +1 it
