### ISSUE TITLE
Tinker tools overwritten while in bag during dimensional transit

### ISSUE THREAD

**Issue by Andr0oS** [Flanks255/simplybackpacks#4]
**Describe the bug**
Tinker's tools in the bag are overwritten when travelling to and from another dimension - specifically the Twilight Forest. One of them used to be a hammer.

**Screenshots**
http://prntscr.com/p59yrx
taken out of the bag after the error was noticed.

Mod version 1.2.2
Forge Version:  8.0.99.99
FTB Academy modpack

**Comment by Flanks255** [comment]
A few questions, as this is very puzzling...
Is this on a server or in single player?
what did the hammer turn in to?
what slot was it in in the backpack?
does it happen everytime? is it only tinkers tools?

**Comment by Andr0oS** [comment]
It happens consistently with Tinker's tools, but it may also have overwritten an astral sorcery impulsion wand with an ender pouch. Most other items seem unaffected, but items with complex nbt data are definitely most likely to be changed.
I'm playing in singleplayer.
I haven't been able to replicate it every time, but it seems to happen more often when moving tools/weapons around immediately before dimensional transit. I think it was in slots 15/16, but I can't say for sure.
The hammer turned into a shuriken once, and after restoring the item from a backup via nbtexplorer, and playing for several hours more, the shuriken turned into a hammer. In both cases the nbt contents of each item were wholly overwritten with the exception of the tinker tool leveling exp data.

**Comment by Flanks255** [comment]
Still cant reproduce it, have you added any mods to the modpack?

**Comment by Andr0oS** [comment]
Nope, no other mods than what's in the Academy modpack. I'll try to see if I can replicate it again later this week.

**Comment by Andr0oS** [comment]
I can't seem to get it to do it again, even loading up on multiple tools, and using all different kinds of tools and dimensional transit, and I can't think of any other factors that might have been involved. I even tried loading up on a bunch of different items with large amounts of NBT data, and different coloured wool, anything I could think of really.
