### ISSUE TITLE
Config with balcklist/whitelist

### ISSUE THREAD

**Issue by Lovatic123** [Flanks255/simplybackpacks#41]
It would be amazing if the mod had a config option to allow certain stuff to go into the backpacks, like modded stuff or shulker boxes. Currently the fishing rods from the aquaculture mod cant go into the bags.

Minecraft 1.16.5.

**Comment by Flanks255** [comment]
Ya, this is on my list of things to put back in, i had this in 1.12, but the config system changed since then, and i rewrote the entire mod.

i should be able to do it pretty quickly, im mainly gonna be using tags to block items soon, but with the whitelist/blacklist on top of that.

**Comment by Flanks255** [comment]
done in 1.5.0
