### ISSUE TITLE
Items not staying in bag when clicked in OR SHIFT-clicked

### ISSUE THREAD

**Issue by Mechrior** [Flanks255/simplybackpacks#45]
**Describe the bug**
When trying to either drop items in or shift-click them in, they appear in the bag, but once the UI is closed, and sometimes a few seconds after and interacting with something like a crafting table or other interactable item, the items I just put in re-appear in my inventory, or pop out around me and i pick them back up.

**Screenshots**
not screenshotable as it happens randomly and quickly.

If it is a crash, please provide the crash-log through a website like http://pastebin.com or https://gist.github.com/
No crash, but happens to me & my partner on a LAN hosted instance of the modpack.

Please provide the version of forge used, and the mod version.
Forge: 36.2.22 (1.16.5)
Mod Version: 2.6.11.2

**Comment by Flanks255** [comment]
Ive never seen version "2.6.11.2" before, but i feel like this is just a fluke or some kind of race condition, no ones ever reported anything like this before, and i cant reproduce it, if you find a way to make it repeatable let me know.

**Comment by Mechrior** [comment]
sorry was looking at simply jetpacks.
Simple backpacks version is: 1.16.5-2.0.1-build.27

**Comment by Flanks255** [comment]
does it happen to both of you, or just you? are you the one hosting the lan game, or joining it.

**Comment by Mechrior** [comment]
Happens to both of us, I am the host, with her joining.

**Comment by Flanks255** [comment]
could you attach your simplybackpacks_backpack_data.dat file? its under the world save, in the data folder. 
![image](https://user-images.githubusercontent.com/32142731/149597862-4999c39d-d0a7-4177-b8f6-6475cd3612be.png)

edit: also if you could, the latest.log file from a recent play session, i think i know what it is, but i want to confirm.

**Comment by Mechrior** [comment]
[simplybackpacks_backpack_data.zip](https://github.com/Flanks255/simplybackpacks/files/7873841/simplybackpacks_backpack_data.zip)
[latest.log](https://github.com/Flanks255/simplybackpacks/files/7873842/latest.log)

Hope these help

**Comment by Flanks255** [comment]
do you only open the backpack via hotkey?, what tier are the backpacks?

**Comment by Mechrior** [comment]
yes they are on the "back" bauble slot, and opened via hotkey.
bth backpacks are currently "diamond" tier

**Comment by Flanks255** [comment]
try pulling it out and opening it via right clicking it in your hand, should fix it., in the datafile it was still a common tier, so only the first 18 slots were usable.
![image](https://user-images.githubusercontent.com/32142731/149602492-e646c268-0937-4e05-aacf-e223498cfebf.png)

**Comment by Mechrior** [comment]
o.O that immediatly fixed them.

We had nt opened them by "hand" after upgrading them, didnt realise we nneeded too, or is that just a failure of the back to recognise the upgrade?

**Comment by Flanks255** [comment]
at the moment the upgrade and migration code is only in the open by hand code, the hotkey doesnt do those checks yet, didnt anticipate the hot key being used exclusively :P
Related to #43

**Comment by Mechrior** [comment]
I am a bit of a hotkey fan, many of my hotkeys in miinecarft are bound to my stream deck so i dont forget them.

Always love using a hotkey mid game than having the shuffle things in my inventory by hand.

**Comment by Flanks255** [comment]
Fixed in 2.0.2 in 1.16 / 1.18
