### ISSUE TITLE
Items popping back into inventory or dropping on ground

### ISSUE THREAD

**Issue by ReeceWilson** [Flanks255/simplybackpacks#47]
I have the rare backpack. But once I put items in that would fill the bag up past 33 item slots, everything past that kicks back into my inventory the next time that I open the backpack. Also, when I click and drag items into the backpack, no matter how many items are in it, they just shoot out onto the ground when I close the backpack. This doesn't happen when I shift click to input items.

**Comment by Flanks255** [comment]
what version of the mod?

**Comment by ReeceWilson** [comment]
Playing on the FTB Endeavor pack 1.9.0 and the version of simplybackpacks is 1.16.5-2.0.1-build.27

**Comment by Flanks255** [comment]
im assuming you are opening the backpack via hotkey and not in hand?

**Comment by ReeceWilson** [comment]
Correct. I just tried it with the backpack in hand and it seemed to work fine. I can't recreate the issue right now, but it has been somewhat sporadic. Others on the server have noticed the same thing with their various sized backpacks though.

**Comment by Flanks255** [comment]
so, that bug was fixed in 2.0.2, the workaround for 2.0.1 is to open it in hand at least once after upgrading it, as opening it finishes the upgrade.
