### ISSUE TITLE
[Feature Request] Auto-pickup when equipped in curio slot.

### ISSUE THREAD

**Issue by isaaclepes** [Flanks255/simplybackpacks#48]
Requesting that the auto-pickup feature work when the backpack is equipped into the curios back slot.  Currently, auto-pickup only works when the bag is in one of the hotbar slots.

**Comment by Flanks255** [comment]
it does work in curio slots.

**Comment by isaaclepes** [comment]
I must be having a bug with it, then.  I can place the bag into and open it from the curio slot, but auto pickup of items doesn't work nor does the hotkey I assigned for the toggle function unless its in a numbered slot.

**Comment by isaaclepes** [comment]
I tried deleting all files for simplybackpacks and redownloading it.  Now everything is working with auto-pickup except the hotkey toggle, which still only works when in the hotbar.  I am happy with it picking items up now and the toggle isn't critical.

I appreciate your response.. it got me thinking of it as a problem not a missing feature.

**Comment by Flanks255** [comment]
does it toggle on when you hit it? do you have other backpacks in your inventory?
it worked fine toggling from curio when i just tested on my server, the hotkey priority goes... Mainhand > offhand > curio > hotbar > inventory

**Comment by isaaclepes** [comment]
Ok, I have it sorted out now.  I was using the 'c' key, which was also assigned to 'save hotbar activator'.  Although that is a Creative mode hotkey, and I am in survival mode, it was gaining priority for the 'c' assignment while the bag was in a curio slot, but not when it was on the hotbar.  Clearing the 'save hotbar activator' assignment solved the issue.

**Comment by Flanks255** [comment]
nice 👍
