### ISSUE TITLE
server issues

### ISSUE THREAD

**Issue by hachiimann** [Flanks255/simplybackpacks#49]
**Describe the bug**
duping due to auto pick up attempting to pick up items and still leaving them on the floor.

**Screenshots**

Please try to give as much info as possible.
- maybe as a server we can get a option in config to disable this for all players so we can use the mod with no issue

If it is a crash, please provide the crash-log through a website like http://pastebin.com or https://gist.github.com/

Please provide the version of forge used, and the mod version.
for mod version its on ftb ultimate anniversary edition using 1.16.5-2.0-1 - build.27
forge version 36.2.26

**Comment by Flanks255** [comment]
> maybe as a server we can get a option in config to disable this for all players so we can use the mod with no issue

disable what exactly?

Also this is a problem ive seen twice before, but no one has ever been able to reproduce it, its likely some lag based race condition, or some weird corner case interaction with another mod.
