### ISSUE TITLE
curios slot does not appear, can't put backpack there

### ISSUE THREAD

**Issue by suneyedset** [Flanks255/simplybackpacks#51]
Minecraft version 1.16.1
curious version curios-FORGE-1.16.1-3.0.0.2
simplybackpacs version 1.4.10

mod does not register a slot with the curious api. No slot appears when clicking on the icon in the user image in inventory (curious button is there, slot does not appear)
cannot wear backpack

**Screenshots**

Please try to give as much info as possible.

If it is a crash, please provide the crash-log through a website like http://pastebin.com or https://gist.github.com/

Please provide the version of forge used, and the mod version.

**Comment by Flanks255** [comment]
curios support was added in version 2.0.0, which is for mc 1.16.5 unfortunately.
