### ISSUE TITLE
Curio Specific Hotkey / MultivBackpack Support 

### ISSUE THREAD

**Issue by Naralas-zz** [Flanks255/simplybackpacks#52]
Currently the hotkey setup seems to specifically only open your most recent backpack, which is neat, but perhaps the GUI could use a small change where there are tabs for other backpacks? Perhaps you could scroll through them with TAB? I understand this might be harder than it sounds because if a bag is somehow dropped or lost after the GUI opens it could cause a problem, or loading items in ways that might be recursive could be an issue, so a simpler solution may just be:

If the mod detects curios / baubles, the "open backpack" button (or a secondary hotkey) could link specifically to the one you are wearing rather than the last one you opened?

**Comment by Flanks255** [comment]
So, the hotkey uses a priority when deciding which backpack to open, as seen here: [Backpackutils.java](https://github.com/Flanks255/simplybackpacks/blob/b99c7e91347fa25c2ecfa0a4add6d0329b5a48b1/src/main/java/com/flanks255/simplybackpacks/util/BackpackUtils.java#L42-L66)

it goes:
- Main hand
- Off hand
- Curios
- Hotbar
- the rest of the inventory.

The rest of what you mention is something ive toyed around with, and is actually in #42 as well.
there are no issues, as the items are not stored within the item anymore, the item is just an ID key to access the storage.

**Comment by Naralas-zz** [comment]
You say it prefers the curio backpack already but having used this mod in a few modpacks, that is not my experience at all. It seems to prefer whichever one I looked into last, which makes the one on my back almost less useful, because as soon as I browse another backpack I have to unequip the curio backpack and open it.

**Comment by Flanks255** [comment]
The mod does not keep track of what backpack was used last, like i said, the priority goes, Mainhand > offhand > curios > hotbar > rest of inventory.

So if you had one in your mainhand/offhand, that would open instead.

**Comment by Naralas-zz** [comment]
I understood what you meant it just did not match my experience with the
mod at all. If I were able to replicate my issue with a video would that be
helpful?

**Comment by Naralas-zz** [comment]
**Sincerest apologies.**

I tried to recreate my issue in a new world, and in one of the modpacks I had come across it, and it appears everything works _exactly_ as you intended. I believe what was really happening was that I would often check the contents of a held backpack, then attempt to open my curios backpack to compare contents or move contents, and it would open the backpack I was previously looking in, (but only because it was still in my main hand, naturally)

However, I guess my gripe does somewhat remain: _why?_ If the item is in my main hand, then hitting the backpack hotkey does not really offer any benefit I can see over simply rightclicking. The only time I can see a need to open a backpack in my main hand with the hotkey is if you were sneaking, and absolutely needed to open that backpack without stopping the sneak, which is a moot point as you stop sneaking as soon as the GUI opens anyway.

Also, the backpack hotkey does not appear to work on backpacks that have not been opened or initialized yet, which is hardly a major issue, and may serve a design purpose, but is just a quirk i noticed while messing around with the mod this morning.

**Comment by Flanks255** [comment]
> However, I guess my gripe does somewhat remain: _why?_ If the item is in my main hand, then hitting the backpack hotkey does not really offer any benefit I can see over simply rightclicking. The only time I can see a need to open a backpack in my main hand with the hotkey is if you were sneaking, and absolutely needed to open that backpack without stopping the sneak, which is a moot point as you stop sneaking as soon as the GUI opens anyway.

so, mainly because that function is also used for the pickup toggle hotkey, to figure out which backpack to toggle, in which case prioritizing the mainhand makes sense, i suppose i should separate it a bit, since opening doesn't make sense.



> Also, the backpack hotkey does not appear to work on backpacks that have not been opened or initialized yet, which is hardly a major issue, and may serve a design purpose, but is just a quirk i noticed while messing around with the mod this morning.

this is because the backpack doesn't technically exist until you open it, the first time you open it its initialized, i need to add a tooltip or something to show when its not been opened yet.
