### ISSUE TITLE
Text UI language key error

### ISSUE THREAD

**Issue by AnzhiZhang** [Flanks255/simplybackpacks#53]
**Describe the bug**
When I try to open or recover a deleted backpack from chat area, it will display the translation key `simplebackpacks.invaliduuid`.

The correct key is `simplybackpacks.invaliduuid`.

**Screenshots**
![image](https://user-images.githubusercontent.com/37402126/167251489-ba157e20-d70f-43f1-b391-0486fcc3a565.png)

**How to fix**
You should correct line 49 in `com.flanks255.simplybackpacks.commands.Open` class, and line 50 in `com.flanks255.simplybackpacks.commands.Recover` class.
```java
ctx.getSource().sendFailure(new TranslatableComponent("simplebackpacks.invaliduuid"));
```

Please provide the version of forge used, and the mod version.
The mod version is 1.16-2.1.0-build.37

I don't want to send a PR because I am lazy :)
But if you would like to include me in the commit message, I would appreciate it.
```
Andy Zhang <37402126+AnzhiZhang@users.noreply.github.com>
```

**Comment by Flanks255** [comment]
Well that was quick, ya, I guess I missed those 2, I found the typo while I was working on the delete command, guess I forgot the other 2, I blame github copilot haha
