### ISSUE TITLE
[question] filters 'only' via mod config?

### ISSUE THREAD

**Issue by rlesch** [Flanks255/simplybackpacks#58]
not sure if i miss something, the autopickup filters have to be done vie teh config files, right?
theres no lazy/comfortable ingame gui to directly mark/pick items as allowed/forbidden? 
(could be also considered as suggestion)

**Comment by Flanks255** [comment]
sneak right click the backpack, that opens the filter screen, the configs are just for things that should never be allowed in the backpack.

**Comment by rlesch** [comment]
a good to know, thanks. it would be helpful to put that information somewhere on the modpage ;) (at last i didnt see it)
