### ISSUE TITLE
Opening a backpack passes clicks through to the world

### ISSUE THREAD

**Issue by quat1024** [Flanks255/simplybackpacks#6]
**Describe the bug**
* Hold a bag in your main hand and a block in your other hand.
* Right click.
* You open the bag and place the block at the same time.

Happens with anything that has a right click behavior (this is pretty disastrous with a CAD from Psi, for example x) )

**What I expected would happen**
You wouldn't place the block.

**Fix**
Return `SUCCESS` instead of calling `super` here: https://github.com/Flanks255/simplybackpacks/blob/818d5031f34dc81406d20e2e6a5bdf5b822c251e/src/main/kotlin/com/flanks255/simplybackpacks/items/ItemBackpackBase.kt#L91

**Versions**
Simply Backpacks 1.2.2
Forge 14.23.5.2648
(it's in FTB Academy with a bunch of other mods added but I don't think the exact modlist is important)

**Comment by Flanks255** [comment]
Nice catch, ill test it out and update it sometime soon.

**Comment by RepoDraghon** [comment]
Yes, this happens with offhand (which is what it's called) items, I keep placing my torches... shift+click is also doing this...

**Comment by Flanks255** [comment]
Sorry for the delay, forgot about the problem.
Fixed in:
1.16.1: 6cde85e
1.15.2: b66f9b1
1.14.4: 53c0aa6
1.12.2: bdfeaf6
