### ISSUE TITLE
[1.16.5] Multiplayer server ResourceLocation no such method error when config for "ItemWhitelist" is set

### ISSUE THREAD

**Issue by Colin-J-Wood** [Flanks255/simplybackpacks#60]
**Describe the bug**
The server will crash trying to load if you have config values set for simply backpack's allow list.  I was using this to allow shulker boxes.  This crash does not occur in singleplayer and the config also works as expected in singleplayer.

https://pastebin.com/YhQ530NB

**Comment by Colin-J-Wood** [comment]
current config (for your own testing purposes)

https://pastebin.com/XVPPXq2Q

**Comment by Flanks255** [comment]
Fixed, version 2.1.2 uploaded to curse, should get approved eventually, this was cause by mojang in their infinite wisdom making the validate method client-side only in 1.16

**Comment by Colin-J-Wood** [comment]
thank you so much for jumping back to this version to fix it, it's much appreciated :)
