### ISSUE TITLE
Simply backpacks crash

### ISSUE THREAD

**Issue by Nuclear4Hurricane** [Flanks255/simplybackpacks#61]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  wings (wings-1.1.5-1.12.2.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.9.6-core.jar)
  SteveKunGLibPlugin (SteveKunG's-Lib-1.12.2-1.1.9.jar)
  MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  Backpacked (backpacked-1.4.3-1.12.2.jar)
  ObfuscatePlugin (obfuscate-0.4.2-1.12.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  LucraftCoreCoreMod (LucraftCore-1.12.2-2.4.17.jar)
  Plugin (NotEnoughIDs-1.5.4.4.jar)
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.281.jar)
  PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50.jar)
  Techguns Core (techguns-1.12.2-2.0.2.0_pre3.2.jar)
  BewitchmentFMLLoadingPlugin (bewitchment-1.12.2-0.0.22.49.jar)
Contact their authors BEFORE contacting forge

// Uh... Did I do that?

Time: 12/25/23 12:25 PM
Description: Initializing game

java.lang.NoClassDefFoundError: kotlin/TypeCastException
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:539)
	at sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:595)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: kotlin.TypeCastException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 38 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 40 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:539)
	at sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:595)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 8 (amd64) version 6.2
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2495179280 bytes (2379 MB) / 3556769792 bytes (3392 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=64M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 Optifine OptiFine_1.12.2_HD_U_G5 150 mods loaded, 149 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                       | Version                | Source                                               | Signature                                |
	|:----- |:------------------------ |:---------------------- |:---------------------------------------------------- |:---------------------------------------- |
	| LC    | minecraft                | 1.12.2                 | minecraft.jar                                        | None                                     |
	| LC    | mcp                      | 9.42                   | minecraft.jar                                        | None                                     |
	| LC    | FML                      | 8.0.99.99              | forge-1.12.2-14.23.5.2860.jar                        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | forge                    | 14.23.5.2860           | forge-1.12.2-14.23.5.2860.jar                        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | micdoodlecore            |                        | minecraft.jar                                        | None                                     |
	| LC    | backpacked               | 1.4.2                  | backpacked-1.4.3-1.12.2.jar                          | None                                     |
	| LC    | obfuscate                | 0.4.2                  | minecraft.jar                                        | None                                     |
	| LC    | techguns_core            | 1.12.2-1.0             | minecraft.jar                                        | None                                     |
	| LC    | voxelmap                 | 1.9.25                 | forgemod_VoxelMap-1.9.28_for_1.12.2.jar              | None                                     |
	| LC    | jei                      | 4.16.1.302             | jei_1.12.2-4.16.1.302.jar                            | None                                     |
	| LC    | abyssalcraft             | 1.10.0                 | AbyssalCraft-1.12.2-1.10.0.jar                       | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| LC    | aoa3                     | 3.0                    | Advent-of-Ascension-Mod-1.12.2.jar                   | None                                     |
	| LC    | aether_legacy            | 1.5.2                  | aether-1.12.2-v1.5.2.jar                             | None                                     |
	| LC    | aether_legacy_addon      | 1.12.2-v1.3.0          | Aether+Continuation+v1.3.0.jar                       | None                                     |
	| LC    | orbis-lib                | 0.2.0                  | orbis-lib-1.12.2-0.2.0+build411.jar                  | db341c083b1b8ce9160a769b569ef6737b3f4cdf |
	| LC    | aether                   | 0.3.0                  | aether_ii-1.12.2-0.3.0+build411-universal.jar        | db341c083b1b8ce9160a769b569ef6737b3f4cdf |
	| LC    | codechickenlib           | 3.2.3.358              | CodeChickenLib-1.12.2-3.2.3.358-universal.jar        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | avaritia                 | 3.3.0                  | Avaritia-1.12.2-3.3.0.33-universal.jar               | None                                     |
	| LC    | backpack                 | 3.0.2                  | backpack-3.0.2-1.12.2.jar                            | None                                     |
	| LC    | baubles                  | 1.5.2                  | Baubles-1.12-1.5.2.jar                               | None                                     |
	| LC    | baubleshud               | 5.0.2                  | BaublesHud-1.12.2-5.0.2.jar                          | None                                     |
	| LC    | betterquesting           | 3.5.329                | BetterQuesting-3.5.329.jar                           | None                                     |
	| LC    | thaumcraft               | 6.1.BETA26             | Thaumcraft-1.12.2-6.1.BETA26.jar                     | None                                     |
	| LC    | botania                  | r1.10-363              | Botania+r1.10-363.jar                                | None                                     |
	| LC    | llibrary                 | 1.7.19                 | llibrary-1.7.19-1.12.2.jar                           | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LC    | mowziesmobs              | 1.5.8                  | mowziesmobs-1.5.8.jar                                | None                                     |
	| LC    | patchouli                | 1.0-22                 | Patchouli-1.0-22.jar                                 | None                                     |
	| LC    | betteranimalsplus        | 9.0.1                  | betteranimalsplus-1.12.2-9.0.1.jar                   | None                                     |
	| LC    | bewitchment              | 0.22.49                | bewitchment-1.12.2-0.0.22.49.jar                     | None                                     |
	| LC    | bibliocraft              | 2.4.5                  | BiblioCraft[v2.4.5][MC1.12.2].jar                    | None                                     |
	| LC    | bountifulbaubles         | 0.0.1                  | Bountiful Baubles-1.12.2-0.1.5.jar                   | None                                     |
	| LC    | redstoneflux             | 2.1.1                  | RedstoneFlux-1.12-2.1.1.1-universal.jar              | None                                     |
	| LC    | brandonscore             | 2.4.19                 | BrandonsCore-1.12.2-2.4.19.214-universal.jar         | None                                     |
	| LC    | btg                      | 1.1.1                  | By+The+Gods-1.12.2-1.1.1.jar                         | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| LC    | chococraft               | 0.9.1.52               | chococraft_1.12.1-0.9.1.52.jar                       | None                                     |
	| LC    | neid                     | 1.5.4.4                | NotEnoughIDs-1.5.4.4.jar                             | None                                     |
	| LC    | phosphor-lighting        | 1.12.2-0.2.6           | phosphor-1.12.2-0.2.6+build50.jar                    | f0387d288626cc2d937daa504e74af570c52a2f1 |
	| LC    | cqrepoured               | 2.1.3B                 | Chocolate_Quest_Repoured-1.12.2-2.1.3B.jar           | None                                     |
	| LC    | christmasfestivity       | 1.2.10                 | christmasfestivity-1.2.10-1.12.2.jar                 | None                                     |
	| LC    | christmasitems           | 0.2.0                  | ChristmasItems020.jar                                | None                                     |
	| LC    | cofhcore                 | 4.6.6                  | CoFHCore-1.12.2-4.6.6.1-universal.jar                | None                                     |
	| LC    | cofhworld                | 1.4.0                  | CoFHWorld-1.12.2-1.4.0.1-universal.jar               | None                                     |
	| LC    | extendedrenderer         | v1.0                   | coroutil-1.12.1-1.2.37.jar                           | None                                     |
	| LC    | coroutil                 | 1.12.1-1.2.37          | coroutil-1.12.1-1.2.37.jar                           | None                                     |
	| LC    | configmod                | v1.0                   | coroutil-1.12.1-1.2.37.jar                           | None                                     |
	| LC    | crafttweaker             | 4.1.20                 | CraftTweaker2-1.12-4.1.20.607.jar                    | None                                     |
	| LC    | ctgui                    | 1.0.0                  | CraftTweaker2-1.12-4.1.20.607.jar                    | None                                     |
	| LC    | crafttweakerjei          | 2.0.3                  | CraftTweaker2-1.12-4.1.20.607.jar                    | None                                     |
	| LC    | ctm                      | MC1.12.2-1.0.2.31      | CTM-MC1.12.2-1.0.2.31.jar                            | None                                     |
	| LC    | customnpcs               | 1.12                   | CustomNPCs_1.12.2-(05Jul20).jar                      | None                                     |
	| LC    | thedalekmod              | (Update 62.1.0)        | Dalek+Mod+-+Update+62.1.jar                          | None                                     |
	| LC    | ptrmodellib              | 1.0.4                  | PTRLib-1.0.4.jar                                     | None                                     |
	| LC    | props                    | 2.6.3                  | Decocraft-2.6.3_1.12.2.jar                           | None                                     |
	| LC    | wiki                     | 1.0                    | Digimobs-1.1.8d.jar                                  | None                                     |
	| LC    | digimobs                 | 1.1.8d                 | Digimobs-1.1.8d.jar                                  | None                                     |
	| LC    | thermalfoundation        | 2.6.7                  | ThermalFoundation-1.12.2-2.6.7.1-universal.jar       | None                                     |
	| LC    | draconicevolution        | 2.3.27                 | Draconic-Evolution-1.12.2-2.3.27.353-universal.jar   | None                                     |
	| LC    | dragonmounts             | 1.12.2-1.6.3           | DragonMounts2-1.12.2-1.6.3.jar                       | None                                     |
	| LC    | mocreatures              | 12.0.5                 | DrZharks+MoCreatures+Mod-12.0.5.jar                  | None                                     |
	| LC    | ebwizardry               | 4.3.11                 | ElectroblobsWizardry-4.3.11.jar                      | None                                     |
	| LC    | ageofabyssalcraft        | 0.7                    | Engender+Mod-1.12.2-0.7-pre1.jar                     | None                                     |
	| LC    | ageofchaos               | 0.7                    | Engender+Mod-1.12.2-0.7-pre1.jar                     | None                                     |
	| LC    | ageofminecraft           | 0.7                    | Engender+Mod-1.12.2-0.7-pre1.jar                     | None                                     |
	| LC    | erebus                   | 1.0.32                 | Erebus-1.0.32.jar                                    | None                                     |
	| LC    | exoticbirds              | 1.0                    | Exotic-Birds-Mod-1.12.2.jar                          | None                                     |
	| LC    | golems                   | 7.1.9                  | ExtraGolems-1.12-7.1.9.jar                           | None                                     |
	| LC    | mantle                   | 1.12-1.3.3.55          | Mantle-1.12-1.3.3.55.jar                             | None                                     |
	| LC    | twilightforest           | 3.11.1021              | twilightforest-1.12.2-3.11.1021-universal.jar        | None                                     |
	| LC    | tconstruct               | 1.12.2-2.13.0.183      | TConstruct-1.12.2-2.13.0.183.jar                     | None                                     |
	| LC    | extrautils2              | 1.0                    | extrautils2-1.12-1.9.9.jar                           | None                                     |
	| LC    | fairylights              | 2.1.10                 | fairylights-2.2.0-1.12.2.jar                         | None                                     |
	| LC    | ftblib                   | 5.4.7.2                | FTBLib-5.4.7.2.jar                                   | None                                     |
	| LC    | ftbutilities             | 5.4.1.130              | FTBUtilities-5.4.1.130.jar                           | None                                     |
	| LC    | cfm                      | 5.3.1                  | furniture-5.3.1-1.12.2.jar                           | None                                     |
	| LC    | galacticraftcore         | 4.0.2.281              | GalacticraftCore-1.12.2-4.0.2.281.jar                | None                                     |
	| LC    | galacticraftplanets      | 4.0.2.281              | Galacticraft-Planets-1.12.2-4.0.2.281.jar            | None                                     |
	| LC    | gargoyles                | 1                      | Gargoyles+mod+1.12.2+patch+1.jar                     | None                                     |
	| LC    | generaldisasters         | 1.0                    | General-Disasters-Mod-Forge-1.12.2.jar               | None                                     |
	| LC    | gravityfalls             | 1.1                    | Gravity+Falls.jar                                    | None                                     |
	| LC    | ichunutil                | 7.2.1                  | iChunUtil-1.12.2-7.2.1.jar                           | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LC    | gravitygun               | 7.0.0                  | GravityGun-1.12.2-7.0.1.jar                          | None                                     |
	| LC    | greatgreekgodsmod        | 1.0.0                  | Great-Greek-Gods-Mod-1.12.2-v.1.0.2.jar              | None                                     |
	| LC    | grimoireofgaia           | 1.7.2                  | GrimoireOfGaia3-1.12.2-1.7.2.jar                     | None                                     |
	| LC    | grunks_grunt_work        | 1.0.0                  | GrunksGruntWork.jar                                  | None                                     |
	| LC    | scp_lockdown_staff       | 1.0.0                  | H2Os+SCPs+1.8.3+Secure+and+Contain+update+part+1.jar | None                                     |
	| LC    | heroicarmory             | 1.1.3                  | heroicarmory-1.2.0.jar                               | None                                     |
	| LC    | hw_inv                   | 1.12.1-1.1.13          | hostileworlds_invasions-1.12.1-1.1.13.jar            | None                                     |
	| LC    | huajiage                 | 1.3.6.2-release        | HuajiAge-InfiniteGalaxy-1.12.2-1.3.6.2-release.jar   | None                                     |
	| LC    | waila                    | 1.8.26                 | Hwyla-1.8.26-B41_1.12.2.jar                          | None                                     |
	| LC    | icbmclassic              | 5.4.0                  | ICBM-classic-1.12.2-5.4.0.jar                        | None                                     |
	| LC    | iceandfire               | 1.7.1                  | iceandfire-1.7.1-1.12.2.jar                          | None                                     |
	| LC    | yba                      | 1.0                    | Implements+of+Extinction+v1.2R-1.12.2.jar            | None                                     |
	| LC    | infinity_gauntlet        | 1.0.0                  | Infinity+Mod+v1.0.0.jar                              | None                                     |
	| LC    | lucraftcore              | 1.12.2-2.4.16          | LucraftCore-1.12.2-2.4.17.jar                        | None                                     |
	| LC    | infinity                 | 1.12                   | infinity-1.12.jar                                    | None                                     |
	| LC    | ironbackpacks            | 1.12.2-3.0.8-12        | IronBackpacks-1.12.2-3.0.8-12.jar                    | None                                     |
	| LC    | jeiintegration           | 1.6.0                  | jeiintegration_1.12.2-1.6.0.jar                      | None                                     |
	| LC    | jojo                     | 1.0.0                  | Jojo_Addons(Beta 0.3)-1.12.2.jar                     | None                                     |
	| LC    | jojobadv                 | 1.1.2                  | JojoBAdv-1.1.2+-+12.2.2.jar                          | None                                     |
	| LC    | joshxmas                 | 1.12.2-1.2.0           | joshxmas-1.12.2-1.2.0b.jar                           | None                                     |
	| LC    | jaff                     | 1.7_for_1.12           | JustAFewFish-1.7_for_1.12.jar                        | None                                     |
	| LC    | lost_aether              | 1.0.2                  | lost-aether-content-1.12.2-1.0.2.jar                 | None                                     |
	| LC    | lycanitesmobs            | 2.0.7.2 - MC 1.12.2    | lycanitesmobs-1.12.2-2.0.7.2.jar                     | None                                     |
	| LC    | mcwbridges               | 1.0.6                  | mcw-bridges-1.0.6b-mc1.12.2.jar                      | None                                     |
	| LC    | mcwfurnitures            | 1.0.1                  | mcw-furniture-1.0.1-mc1.12.2beta.jar                 | None                                     |
	| LC    | mekanism                 | 1.12.2-9.8.3.390       | Mekanism-1.12.2-9.8.3.390.jar                        | None                                     |
	| LC    | minerva                  | 1.0.13                 | minerva-library-1.0.13.jar                           | b851b8b7c7f4d8d0e910ff27618150ba80c026ec |
	| LC    | stevekung's_lib          | 1.1.9                  | SteveKunG's-Lib-1.12.2-1.1.9.jar                     | None                                     |
	| LC    | moreplanets              | 2.2.0                  | More-Planets-1.12.2-2.2.0-GC281.jar                  | None                                     |
	| LC    | morescp                  | 1.0.0                  | morescp.jar                                          | None                                     |
	| LC    | multimob                 | 1.0.5                  | multimob-1.0.5.jar                                   | None                                     |
	| LC    | mutantbeasts             | 1.12.2-0.7.2           | Mutant-Beasts-Mod-1.12.2.jar                         | 25e0dcff5b5a7325d7c28898af41ff8b0ba41b77 |
	| LC    | natura                   | 1.12.2-4.3.2.69        | natura-1.12.2-4.3.2.69.jar                           | None                                     |
	| LC    | projectintelligence      | 1.0.9                  | ProjectIntelligence-1.12.2-1.0.9.28-universal.jar    | None                                     |
	| LC    | nei                      | 2.4.3                  | NotEnoughItems-1.12.2-2.4.3.245-universal.jar        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | harvestcraft             | 1.12.2zb               | Pam's HarvestCraft 1.12.2zb.jar                      | None                                     |
	| LC    | particleman              | 1.12.1-1.5.2           | particleman-1.12.1-1.5.2.jar                         | None                                     |
	| LC    | thepillarmen             | 1.0.0                  | Pillarmenmoddioequipment (2).jar                     | None                                     |
	| LC    | pixelmon                 | 8.4.3                  | Pixelmon-1.12.2-8.4.3-universal.jar                  | None                                     |
	| LC    | tcg                      | 1.12.2-8.4.3-universal | Pixelmon-1.12.2-8.4.3-universal.jar                  | None                                     |
	| LC    | primitivemobs            | 1.2.3a                 | primitivemobs-1.2.3a.jar                             | None                                     |
	| LC    | rustic                   | 1.1.7                  | rustic-1.1.7.jar                                     | None                                     |
	| LC    | rusticwitchcraft         | 1.0.2                  | rusticwitcraft-1.0.2.jar                             | None                                     |
	| LC    | scp_containment_protocol | 1.0.0                  | Scp+Containment+Protocol+1.0.4.jar                   | None                                     |
	| LC    | scootys_scp_mod          | 1.5                    | SCP+Lockdown+Heavy+Expansion+1.5.1.jar               | None                                     |
	| LC    | scp                      | 2.3.1                  | SCP+Lockdown-1.12.2-2.3.1-dev.jar                    | None                                     |
	| LC    | silentlib                | 3.0.13                 | SilentLib-1.12.2-3.0.14+168.jar                      | None                                     |
	| LC    | silentgems               | 2.8.18                 | SilentsGems-1.12.2-2.8.22+327.jar                    | None                                     |
	| L     | simplybackpacks          | 1.4.9                  | simplybackpacks-1.4.9.jar                            | None                                     |
	| L     | sirenheadreturn          | 1.1                    | sirenheadreturnv1.1.jar                              | None                                     |
	| L     | spartanweaponry          | beta 1.3.8             | SpartanWeaponry-1.12.2-beta-1.3.8.jar                | None                                     |
	| L     | spartanfire              | 0.05                   | spartanfire-0.05.jar                                 | None                                     |
	| L     | spartanshields           | 1.5.4                  | SpartanShields-1.12.2-1.5.4.jar                      | None                                     |
	| L     | stygian                  | 1.0.4                  | stygian-1.0.4.jar                                    | None                                     |
	| L     | techguns                 | 2.0.2.0                | techguns-1.12.2-2.0.2.0_pre3.2.jar                   | None                                     |
	| L     | tfspellpack              | 1.1.0                  | TFSpellPack-1.1.0-MC1.12.2.jar                       | None                                     |
	| L     | thermalexpansion         | 5.5.7                  | ThermalExpansion-1.12.2-5.5.7.1-universal.jar        | None                                     |
	| L     | tropicraft               | 7.1.9.115              | tropicraft-MC1.12.2-7.1.9.115.jar                    | None                                     |
	| L     | tschipplib               | 1.1.3                  | TschippLib MC1.12.2 v1.1.3.jar                       | None                                     |
	| L     | vampirism                | 1.6.2                  | Vampirism-1.12.2-1.6.2.jar                           | None                                     |
	| L     | teamlapen-lib            | 1.6.2                  | Vampirism-1.12.2-1.6.2.jar                           | None                                     |
	| L     | vehicle                  | 0.44.1                 | vehicle-mod-0.44.1-1.12.2.jar                        | None                                     |
	| L     | weather2                 | 1.12.1-2.6.12          | weather2-1.12.1-2.6.12.jar                           | None                                     |
	| L     | wings                    | 1.1.5                  | wings-1.1.5-1.12.2.jar                               | None                                     |
	| L     | bauble_wings             | 1.0.0                  | wings-1.1.5-1.12.2.jar                               | None                                     |
	| L     | zerascp                  | 1.0.0                  | zeras-SCPs-1.7.1.jar                                 | None                                     |
	| L     | gogredux                 | 1.0.0                  | gogredux-1.12.2-1.0.0.jar                            | None                                     |
	| L     | rebornmod                | 1.3.0                  | JurassicWorldReborn-1.12.2-1.3.0.jar                 | None                                     |
	| L     | thebetweenlands          | 3.9.6                  | TheBetweenlands-3.9.6-universal.jar                  | None                                     |
	| UD    | mobends_wings            | 1.0.0                  | wings-1.1.5-1.12.2.jar                               | None                                     |

	Loaded coremods (and transformers): 
wings (wings-1.1.5-1.12.2.jar)
  me.paulf.wings.server.asm.WingsRuntimePatcher
  me.paulf.wings.server.asm.mobends.WingsMoBendsRuntimePatcher
TheBetweenlandsLoadingPlugin (TheBetweenlands-3.9.6-core.jar)
  thebetweenlands.core.TheBetweenlandsClassTransformer
SteveKunGLibPlugin (SteveKunG's-Lib-1.12.2-1.1.9.jar)
  
MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  mekanism.coremod.KeybindingMigrationHelper
Backpacked (backpacked-1.4.3-1.12.2.jar)
  com.mrcrayfish.backpacked.asm.BackpackedTransformer
ObfuscatePlugin (obfuscate-0.4.2-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
LucraftCoreCoreMod (LucraftCore-1.12.2-2.4.17.jar)
  lucraft.mods.lucraftcore.core.LCTransformer
Plugin (NotEnoughIDs-1.5.4.4.jar)
  ru.fewizz.neid.asm.Transformer
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.281.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50.jar)
  
Techguns Core (techguns-1.12.2-2.0.2.0_pre3.2.jar)
  techguns.core.TechgunsASMTransformer
BewitchmentFMLLoadingPlugin (bewitchment-1.12.2-0.0.22.49.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 546.01' Renderer: 'NVIDIA GeForce GTX 1650/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- wailaIntegration (Enabled/Not Forced)

	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)

	Launched Version: 1.12.2-forge-14.23.5.2860
	LWJGL: 2.9.4
	OpenGL: NVIDIA GeForce GTX 1650/PCIe/SSE2 GL version 4.6.0 NVIDIA 546.01, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i3-9100F CPU @ 3.60GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 546.01
	OpenGlRenderer: NVIDIA GeForce GTX 1650/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by Flanks255** [comment]
The 1.12 version needs forgelin, https://www.curseforge.com/minecraft/mc-mods/shadowfacts-forgelin/files/2785465
