### ISSUE TITLE
how do you stop sharing 1 inventory with the backpack  with other people i just  had this problem with the diamond upgrade its 

### ISSUE THREAD

**Issue by DiamondLevi** [Flanks255/simplybackpacks#62]
i play on my sever with my friend and we both have the diamond upgrade i we just discorverd that we share it i tried multiple thing whith the shift right click menu but nothing changed

**Comment by Flanks255** [comment]
It sounds like the backpack was duplicated via creative mode, or something else, which would cause both backpacks to have the same ID, which would cause them to share inventory.

**Comment by DiamondLevi** [comment]
i think i did not do that but maybe i forgot but i will let my friend craft a new back pack to see if that works

**Comment by DiamondLevi** [comment]
it worked i could have sworn i crafted both at level 1 maybe that does the same thing but i least now we have our own backpack thank you

**Comment by Flanks255** [comment]
Creative mode duplicating is the only thing i can think of, as a new backpack, the first time its opened, picks a random UUID, which is a very big number, [wikipedia](https://en.wikipedia.org/w/index.php?title=Universally_unique_identifier&oldid=755882275#Random_UUID_probability_of_duplicates)

so if a backpack was duplicated after it was opened, you would end up with 2 backpacks with the same UUID, and thus the same inventory, 2 backpacks randomly picking the same number is improbably.
