### ISSUE TITLE
[1.14.4] Backpacks void Items that are added to existing Itemstacks

### ISSUE THREAD

**Issue by NielsPilgaard** [Flanks255/simplybackpacks#8]
**Describe the bug**
The first time you put items in the Backpack it's fine, but when you try to add to those existing items (after closing) the amount you added just disappears after re-opening.

**Versions**
Forge 1.14.4-28.1.109
simplybackpacks-1.14.4-1.3.0

Original issue: https://github.com/NillerMedDild/Enigmatica4/issues/282

**Comment by Flanks255** [comment]
Hmm, does this only happen on a server? cause i just loaded that pack up and cant replicate the issue in single player.

**Comment by NielsPilgaard** [comment]
I haven't tried on a server, this was in single player.

**Comment by Cheata** [comment]
NillerMedDild has asked me to add my experience to this as well I was vaguely aware of the voiding items added to existing stacks as every so often i would check the backpack and think to myself  "there should be more stuff in here" however the main issue i noticed was the backpack either partially or completely voiding on payer death or logout.

I have also found that this behavior seems to be prevented (the backpack retains its contents) if the backpack is kept off the active toolbar and the auto collect is turned off.

I will also mention that the auto collect doesn't seem to operate when the backpack is not on the active toolbar but i'm not sure if this is intended behavior or even related.

I am running a linux server Debian 9 (stretch)
mod pack: Enigmatica 4 0.4.4
minecraft 1.14.4
forge-1.14.4-28.1.109

If you think it would help email me your uuid and username and i can add you to the whitelist and give you access to my server to observe the issue.

**Comment by RobertSkalko** [comment]
same here, on singleplayer, shift clicking diamonds nulls them :/

I knew i had about 10 diamonds less than i remembered..

**Comment by Flanks255** [comment]
looking into both of the issues, but still unable to reproduce either of them as of yet.

**Comment by NielsPilgaard** [comment]
I can reproduce it with just JEI and Simply Backpacks in 1.15.2
I've made a video, just a sec I'll upload it to drive
https://drive.google.com/open?id=1VKgJEanMYWObSfS5p63Lw1JF2yybT44G

**Comment by Flanks255** [comment]
perfect, thanks to the video i can reproduce it every time now, now its just a matter of figuring out what the heck is happening.... and how to fix it...

**Comment by Yamza** [comment]
This seems to still be an issue in the 1.15.2 version as well. This is on a server.
https://uberi.fi/x/PiPanoptesGSW.mp4
forge-31.1.14
simplybackpacks-1.15.2-1.3.0.jar

**Comment by Flanks255** [comment]
ya, im aware, the 1.14 and 1.15 versions are identical, im still working on it, this bug is proving very elusive to fix...

**Comment by VarianArdell** [comment]
I don't know if this helps, but I also have this issue and it only seems to be happening when using the shift-click to auto transfer items from inventory into an already-existing stack in a backpack. if you click and drop the item onto a stack and they merge, then it works fine. at least, this is what is happening on mine, not sure if it's the same for everyone.

EDIT: scratch that, it seems that only works some of the time, and others it voids the newly added items just like if you shift-click...

**Comment by Flanks255** [comment]
This "should" be fixed, i really hope.
1.14: https://www.curseforge.com/minecraft/mc-mods/simply-backpacks/files/2897686
1.15: https://www.curseforge.com/minecraft/mc-mods/simply-backpacks/files/2897681

**Comment by NielsPilgaard** [comment]
You and me both :D

**Comment by NielsPilgaard** [comment]
It is indeed fixes, thanks a bunch!

**Comment by VarianArdell** [comment]
still having this problem in the newest version of the mod, MC version 1.14.4... 
EDIT: it seems the issue (at least for me) is that shift-clicking the items into a preexisting stack isn't updating the bag, but actually dragging and dropping an item into one of those preexisting stacks causes the bag to update and you can shift-click items into those stacks after that... is very bizarre, but should still be looked into
EDIT 2: while this might be a separate bug (just lemme know and I'll post a separate bug report), the aforementioned fix seems to reset upon putting a bag into a Tool Belt (from the mod of the same name)
